export default {
  FETCH_CATEGORY_REQUEST: '@@category/FETCH_CATEGORY_REQUEST',
  FETCH_CATEGORY_SUCCESS: '@@category/FETCH_CATEGORY_SUCCESS',
  FETCH_CATEGORY_FAILURE: '@@category/FETCH_CATEGORY_FAILURE',
  SET_CURRENT_CATEGORY: '@@category/SET_CURRENT_CATEGORY',
  FETCH_CATEGORIES_REQUEST: '@@category/FETCH_CATEGORIES_REQUEST',
  FETCH_CATEGORIES_SUCCESS: '@@category/FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILURE: '@@category/FETCH_CATEGORIES_FAILURE',
  START_AUTO_SLIDING: '@@category/START_AUTO_SLIDING',
  STOP_AUTO_SLIDING: '@@category/STOP_AUTO_SLIDING',
};
